version: '2'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    links:
      - mysql:db
    ports:
      - "0.0.0.0:8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./html:/var/www/html
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITARY=1
    ports:
      - 8081:80
    links:
      - mysql:db
    volumes:
      - ./sessions:/sessions
